FROM confluentinc/cp-kafka-connect:5.1.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-mqtt:latest

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-influxdb:latest