{
 "title": "Dashboard do Tutor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "query": {
     "query": "SELECT distinct(\"uuid\") FROM \"sensors/face\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "A olhar para o ecrã?",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "($yaw >= -5.3 && $yaw <= 2.5)", "type": "math" }
   ]
  },
  {
   "title": "Tempo com os olhos fechados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expression": "($eyes_closed/$total)*100", "type": "math" }
   ]
  },
  {
   "title": "Teclado (CPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "characteres por minuto",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MOVING_AVERAGE(COUNT(\"value_s\"), 5) * 60 FROM \"sensors/keyboard\" WHERE \"uuid\" = '$uuid' AND $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Teclado (DPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "deletes por minuto",
     "query": "SELECT MOVING_AVERAGE(COUNT(\"value_s\"), 5) * 60 FROM \"sensors/keyboard\" WHERE \"uuid\" = '$uuid' AND \"value_s\" = 'delete' AND $timeFilter GROUP BY time(1s) fill(0)"
    }
   ]
  },
  {
   "title": "Smartwatch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "batimentos por minuto",
     "query": "SELECT \"bpm\" FROM \"sensors/hrv\" WHERE \"uuid\" = '$uuid' AND time >= $__from AND $timeFilter"
    }
   ]
  }
 ]
}